"""create_vault_resources_table

Revision ID: 7c25ac0bfac7
Revises: ea2b2e388b9c
Create Date: 2026-06-05 18:54:56.359805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c25ac0bfac7'
down_revision: Union[str, Sequence[str], None] = 'ea2b2e388b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('material_type', sa.Enum('PYQ', 'NOTES', 'LAB', 'OTHER', name='materialtypeenum'), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('approval_status', sa.dialects.postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='approvalstatusenum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vault_resources')
    # ### end Alembic commands ###
